# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1258497197);
user_pref("app.update.lastUpdateTime.background-update-timer", 1258497196);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1258497196);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1258497196);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1258497213);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1258497198);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.1");
user_pref("extensions.enabledItems", "{fc637775-2381-1118-a451-dd123eee5112}:1.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.1");
user_pref("extensions.lastAppVersion", "3.5.1");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1261089200);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
